# Stage 1: Synthetic Exposure Data & Pandas Fundamentals
- Environment Set Up
- Git and Github
- Notebooks vs. Scripts
- Python and Pandas Concepts

## Task
In VS Code, create a new file called build_exposure.py. Using pandas, create a DataFrame with 10 rows representing fake QLD properties, with these columns:
- policy_id (just 1 to 10)
- lat (roughly between -28 and -16, since that covers QLD coastline from the NSW border up to Cairns)
- lon (roughly between 145 and 153, QLD's longitude range)
- construction_type (pick from: "timber", "brick_veneer", "concrete_block")
- sum_insured (any reasonable dollar values, e.g. between 200,000 and 800,000)

In [17]:
# Load Packages
import numpy as np
import pandas as pd

In [18]:
# Checking environment is working properly
print("Hello World!")

Hello World!

In [19]:
# Defining Data
policy_id = np.array([1,2,3,4,5,6,7,8,9,10])

lat = np.random.uniform(-28, -16, size=10)
long = np.random.uniform(145, 153, size=10)

sum_insured = np.random.uniform(2e5, 8e5, size=10)

materials = ["timber", "brick_veneer", "concrete_block"]
construction_type = np.random.choice(materials, size=10)

In [20]:
# Building the DataFrame

# Errors with this attempt
#col_names = ["policy_id", "lat", "long", "construction_type", "sum_insured"]
#df = pd.DataFrame([policy_id, lat, long, sum_insured, construction_type], columns = col_names, size=())

df = pd.DataFrame({
    "policy_id": policy_id,
    "latitude": lat,
    "longitude": long,
    "construction_type": construction_type,
    "sum_insured": sum_insured
})

# Don't need the print statement to see the table in a notebook
df

   policy_id   latitude   longitude construction_type    sum_insured
0          1 -18.363398  152.570645            timber  429195.712315
1          2 -19.337466  149.380952            timber  427128.989878
2          3 -23.054589  146.425911            timber  220024.609738
3          4 -19.892854  146.016992    concrete_block  284916.237604
4          5 -23.398209  148.965804            timber  216411.541382
5          6 -27.404652  147.666006    concrete_block  548309.421277
6          7 -24.793907  147.002699            timber  652286.118850
7          8 -19.159319  149.558731    concrete_block  510675.232764
8          9 -25.106351  148.607311            timber  222475.013362
9         10 -25.597591  145.561328    concrete_block  467589.865296

In [21]:
# use to check column data types
df.dtypes

# use for basic statistics
df.describe()

       policy_id   latitude   longitude    sum_insured
count   10.00000  10.000000   10.000000      10.000000
mean     5.50000 -22.610834  148.175638  397901.274247
std      3.02765   3.193182    2.099840  154510.319302
min      1.00000 -27.404652  145.561328  216411.541382
25%      3.25000 -25.028240  146.570108  238085.319423
50%      5.50000 -23.226399  148.136658  428162.351096
75%      7.75000 -19.476313  149.277165  499903.890897
max     10.00000 -18.363398  152.570645  652286.118850

In [22]:
# Round insured amounts
df["sum_insured"] = df["sum_insured"].round(2)
df["sum_insured"]

0    429195.71
1    427128.99
2    220024.61
3    284916.24
4    216411.54
5    548309.42
6    652286.12
7    510675.23
8    222475.01
9    467589.87
Name: sum_insured, dtype: float64

In [23]:
# Saving data frame to csv
df.to_csv("exposure_data.csv", index=False)